#!/usr/bin/env bash
# tools/bridge_headers.sh — Generate SESSION/DELTA headers for Orchestrator handoff
# Usage: bash tools/bridge_headers.sh [TAG]
#   TAG: optional identifier (default: MANUAL)
# Output: report/SESSION_<TAG>.md, report/DELTA_<TAG>.md

set -euo pipefail

TAG="${1:-MANUAL}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="${REPO_ROOT}/report"
TIMESTAMP="$(date -Iseconds 2>/dev/null || date '+%Y-%m-%dT%H:%M:%S%z')"

mkdir -p "${REPORT_DIR}"

# --- Detect OS ---
detect_os() {
    local os_info=""
    # Check WSL
    if grep -qi microsoft /proc/version 2>/dev/null; then
        os_info="WSL"
    fi
    # Get PRETTY_NAME from /etc/os-release
    if [ -f /etc/os-release ]; then
        local pretty
        pretty=$(grep '^PRETTY_NAME=' /etc/os-release 2>/dev/null | cut -d'"' -f2)
        if [ -n "$pretty" ]; then
            if [ -n "$os_info" ]; then
                os_info="${os_info} + ${pretty}"
            else
                os_info="${pretty}"
            fi
        fi
    fi
    [ -z "$os_info" ] && os_info="unknown"
    echo "$os_info"
}

# --- Git info ---
git_branch() {
    git -C "${REPO_ROOT}" branch --show-current 2>/dev/null || echo "detached"
}

git_head() {
    git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo "unknown"
}

git_status_summary() {
    local porcelain
    porcelain=$(git -C "${REPO_ROOT}" status --porcelain 2>/dev/null)
    if [ -z "$porcelain" ]; then
        echo "clean"
    else
        local added modified deleted untracked
        added=$(echo "$porcelain" | grep -c '^A' || true)
        modified=$(echo "$porcelain" | grep -c '^.M\|^M' || true)
        deleted=$(echo "$porcelain" | grep -c '^.D\|^D' || true)
        untracked=$(echo "$porcelain" | grep -c '^??' || true)
        echo "dirty (+${added} ~${modified} -${deleted} ?${untracked})"
    fi
}

# --- Python info ---
python_system_version() {
    python3 --version 2>/dev/null | awk '{print $2}' || echo "unknown"
}

venv_exists() {
    [ -d "${REPO_ROOT}/.venv" ] && echo "yes" || echo "no"
}

python_venv_version() {
    if [ -d "${REPO_ROOT}/.venv" ]; then
        local venv_python="${REPO_ROOT}/.venv/bin/python"
        if [ -x "$venv_python" ]; then
            "$venv_python" --version 2>/dev/null | awk '{print $2}' || echo "unknown"
        else
            echo "unknown"
        fi
    else
        echo "n/a"
    fi
}

# --- Pytest last ---
pytest_last_line() {
    # Find most recent report/pytest_*.txt by mtime
    local latest
    latest=$(find "${REPORT_DIR}" -maxdepth 1 -name 'pytest_*.txt' -type f 2>/dev/null | \
             xargs ls -t 2>/dev/null | head -n1)
    if [ -n "$latest" ] && [ -f "$latest" ]; then
        local basename_file
        basename_file=$(basename "$latest")
        local last_line
        last_line=$(tail -n1 "$latest" 2>/dev/null | tr -d '\r')
        echo "${basename_file}: ${last_line}"
    else
        echo "unknown (no pytest_*.txt found)"
    fi
}

# --- Gather data ---
OS_INFO=$(detect_os)
GIT_BRANCH=$(git_branch)
GIT_HEAD=$(git_head)
GIT_STATUS=$(git_status_summary)
PYTHON_SYS=$(python_system_version)
VENV_EXISTS=$(venv_exists)
PYTHON_VENV=$(python_venv_version)
PYTEST_LAST=$(pytest_last_line)

# --- Generate SESSION_<TAG>.md ---
SESSION_FILE="${REPORT_DIR}/SESSION_${TAG}.md"
cat > "${SESSION_FILE}" << EOF
# SESSION: ${TAG}

## Environment Snapshot

| Key | Value |
|-----|-------|
| timestamp | ${TIMESTAMP} |
| repo_path | ${REPO_ROOT} |
| os | ${OS_INFO} |
| git_branch | ${GIT_BRANCH} |
| git_head | ${GIT_HEAD} |
| git_status | ${GIT_STATUS} |
| python_system | ${PYTHON_SYS} |
| venv_exists | ${VENV_EXISTS} |
| python_venv | ${PYTHON_VENV} |
| pytest_last | ${PYTEST_LAST} |

## Notes

Generated by \`tools/bridge_headers.sh ${TAG}\`
EOF

echo "Created: ${SESSION_FILE}"

# --- Generate DELTA_<TAG>.md ---
DELTA_FILE="${REPORT_DIR}/DELTA_${TAG}.md"
cat > "${DELTA_FILE}" << EOF
# DELTA: ${TAG}

## Changes Since Last Session

_Placeholder: fill in after work is done._

## Artifacts Provided

- \`report/SESSION_${TAG}.md\`
- \`report/DELTA_${TAG}.md\`

## Verification Status

| Check | Result |
|-------|--------|
| pytest | _pending_ |
| git_status | ${GIT_STATUS} |

## Notes

Generated by \`tools/bridge_headers.sh ${TAG}\`
EOF

echo "Created: ${DELTA_FILE}"
echo "Done. TAG=${TAG}"
