#!/usr/bin/env bash
# tools/list_skips.sh — Inventory pytest skipped tests
# Usage: bash tools/list_skips.sh <TAG>
# Output: report/pytest_rs_<TAG>.txt, report/skips_inventory_<TAG>.md

set -euo pipefail

TAG="${1:-MANUAL}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="${REPO_ROOT}/report"
VENV_DIR="${REPO_ROOT}/.venv"

mkdir -p "${REPORT_DIR}"

# Activate venv if exists
if [ -d "${VENV_DIR}" ]; then
    source "${VENV_DIR}/bin/activate"
fi

PYTEST_RS_FILE="${REPORT_DIR}/pytest_rs_${TAG}.txt"
INVENTORY_FILE="${REPORT_DIR}/skips_inventory_${TAG}.md"

echo "[list_skips] Running pytest -q -rs..."
python -m pytest -q -rs 2>&1 | tee "${PYTEST_RS_FILE}"

echo "[list_skips] Parsing skips to inventory..."

# Parse the -rs output to extract skip reasons
# Format: SKIPPED [N] path/to/file.py::test_name - reason
TAG_VAL="${TAG}" PYTEST_RS_FILE_VAL="${PYTEST_RS_FILE}" INVENTORY_FILE_VAL="${INVENTORY_FILE}" python3 << 'PYEOF'
import re
import os
from pathlib import Path

TAG = os.environ["TAG_VAL"]
rs_file = Path(os.environ["PYTEST_RS_FILE_VAL"])
inventory_file = Path(os.environ["INVENTORY_FILE_VAL"])

content = rs_file.read_text(encoding="utf-8", errors="replace")

# Find SKIPPED lines
# Pattern: SKIPPED [N] path:line: reason
skip_pattern = re.compile(r"SKIPPED \[(\d+)\] ([^:]+:\d+): (.+)")

skips = []
for line in content.split("\n"):
    m = skip_pattern.search(line)
    if m:
        count = int(m.group(1))
        nodeid = m.group(2)
        reason = m.group(3).strip()
        skips.append({"nodeid": nodeid, "reason": reason, "count": count})

# Also try to find lines like: "s tests/..." which is the short format
short_pattern = re.compile(r"^s (.+)$")
for line in content.split("\n"):
    m = short_pattern.match(line)
    if m:
        nodeid = m.group(1).strip()
        if not any(s["nodeid"] == nodeid for s in skips):
            skips.append({"nodeid": nodeid, "reason": "(see -rs output)", "count": 1})

# Generate markdown inventory
lines = [
    f"# Skips Inventory: {TAG}",
    "",
    f"Total skipped: {len(skips)}",
    "",
    "| # | Node ID | Reason |",
    "|---|---------|--------|",
]

for i, s in enumerate(skips, 1):
    nodeid_short = s["nodeid"].split("::")[-1] if "::" in s["nodeid"] else s["nodeid"]
    lines.append(f"| {i} | `{s['nodeid']}` | {s['reason']} |")

lines.append("")
lines.append("---")
lines.append(f"Generated by `tools/list_skips.sh {TAG}`")

inventory_file.write_text("\n".join(lines), encoding="utf-8")
print(f"[list_skips] Wrote {len(skips)} skips to {inventory_file}")
PYEOF

echo "[list_skips] Created: ${PYTEST_RS_FILE}"
echo "[list_skips] Created: ${INVENTORY_FILE}"
echo "[list_skips] Done. TAG=${TAG}"
